services:
  tao-converter:
    image: ${TAO_CONVERTER_IMAGE}
    shm_size: 16g
    ulimits:
      memlock: -1
      stack: 67108864
    runtime: nvidia
    env_file:
      - workspace/.env
    entrypoint: ["bash", "/tmp/entrypoint.sh"]
    volumes:
      - type: bind
        source: facenet_model
        target: /tmp/facenet_model
      - type: bind
        source: fpenet_model
        target: /tmp/fpenet_model
      - type: bind
        source: tlt-converter.sh
        target: /tmp/entrypoint.sh
      - type: bind
        source: triton-models
        target: /models

  triton-server:
    build:
      args:
        - FROM_BASE_IMAGE=${TRITON_SERVER_IMAGE}
        - PROTOBUF_URL=${PROTOBUF_URL}
      context: .
      dockerfile: Dockerfile
    image: triton-server
    shm_size: 16g
    ulimits:
      memlock: -1
      stack: 67108864
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]
    env_file:
      - workspace/.env
    ports:
      - 8000:8000
      - 8001:8001
      - 8002:8002
    entrypoint:
      [
        "tritonserver",
        "--model-repository=/models",
        "--allow-metrics=true",
        "--allow-gpu-metrics=true",
        "--log-verbose=0",
        "--repository-poll-secs=3",
      ]
    hostname: triton-server
    networks:
      triton-server:
        ipv4_address: ${TRITON_SERVER_IP}
    volumes:
      - type: bind
        source: triton-models
        target: /models

  batch-triton-client:
    build:
      args:
        - FROM_BASE_IMAGE=${TRITON_CLIENT_IMAGE}
        - PROTOBUF_URL=${PROTOBUF_URL}
      context: .
      dockerfile: Dockerfile
    image: triton-client
    shm_size: 16g
    ulimits:
      memlock: -1
      stack: 67108864
    env_file:
      - workspace/.env
    entrypoint: ["python", "/workspace/run.py"]
    working_dir: /workspace
    hostname: triton-client
    networks:
      triton-server:
        ipv4_address: ${TRITON_CLIENT_IP}
    volumes:
      - type: bind
        source: workspace
        target: /workspace
      - type: bind
        source: ${HOST_IMAGE_FOLDER}
        target: ${CONTAINER_IMAGE_FOLDER}

  interactive-triton-client:
    build:
      args:
        - FROM_BASE_IMAGE=${TRITON_CLIENT_IMAGE}
        - PROTOBUF_URL=${PROTOBUF_URL}
      context: .
      dockerfile: Dockerfile
    image: triton-client
    runtime: nvidia
    shm_size: 16g
    ulimits:
      memlock: -1
      stack: 67108864
    env_file:
      - workspace/.env
    ports:
      - 8888:8888
    entrypoint:
      [
        "jupyter",
        "lab",
        "--ServerApp.ip=0.0.0.0",
        "--ServerApp.port=8888",
        "--ServerApp.allow_root=True",
        "--ServerApp.token=''",
        "--ServerApp.password=''",
        "--Application.log_level='CRITICAL'",
      ]
    working_dir: /workspace
    hostname: triton-client
    networks:
      triton-server:
        ipv4_address: ${TRITON_CLIENT_IP}
    volumes:
      - type: bind
        source: workspace
        target: /workspace
      - type: bind
        source: ${HOST_IMAGE_FOLDER}
        target: ${CONTAINER_IMAGE_FOLDER}
      

  redis-db:
    image: ${REDIS_DB_IMAGE}
    env_file:
      - workspace/.env
    ports:
      - 6379:6379
    hostname: redis-db
    networks:
      triton-server:
        ipv4_address: ${REDIS_DB_IP}
    volumes:
      - type: bind
        source: redis-db
        target: /data
      - type: bind
        source: redis-db/rejson.so
        target: /usr/lib/redis/modules/rejson.so
      - type: bind
        source: redis-db/redisearch.so
        target: /usr/lib/redis/modules/redisearch.so
      - type: bind
        source: redis-db/redisai.so
        target: /usr/lib/redis/modules/redisai.so
      - type: bind
        source: redis-db/redis.conf
        target: /usr/local/etc/redis/redis.conf
    entrypoint: ["redis-server", "/usr/local/etc/redis/redis.conf"]

# OPTIONAL: https://redis.com/redis-enterprise/redis-insight/
# redis-insight:
#   image: ${REDIS_INSIGHT_IMAGE}
#   env_file:
#     - workspace/.env
#   ports:
#     - 8003:8001
#   hostname: redis-insight
#   networks:
#     triton-server:
#       ipv4_address: ${REDIS_INSIGHT_IP}
#   volumes:
#     - type: bind
#       source: redis-db/rejson.so
#       target: /usr/lib/redis/modules/rejson.so
#     - type: bind
#       source: redis-db/redisearch.so
#       target: /usr/lib/redis/modules/redisearch.so
#     - type: bind
#       source: redis-db/redisai.so
#       target: /usr/lib/redis/modules/redisai.so
#     - type: bind
#       source: redis-db/redis.conf
#       target: /usr/local/etc/redis/redis.conf

networks:
  triton-server:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}
