name: "fpenet_preprocess"
backend: "dali"
default_model_filename: "model.dali"
max_batch_size: 64
dynamic_batching {
  preferred_batch_size: [ 1, 32, 64 ]
  max_queue_delay_microseconds: 50000
}

instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]

input [
    {
      name: "raw_image_data"
      data_type: TYPE_UINT8
      dims: [ -1 ]
      allow_ragged_batch: true
    },
    {
      name: "true_boxes"
      data_type: TYPE_INT32
      dims: [ 4 ]
      allow_ragged_batch: true
    }
  ]

output [
  {
    name: "input_face_images"
    data_type: TYPE_FP32
    dims: [ 1, 80, 80 ]
  }
]